# Generated by Django 5.2.1 on 2025-05-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('isd', models.CharField(default='91', max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(blank=True, max_length=220, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.ManyToManyField(blank=True, null=True, to='accounts.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username',), name='unique_active_username'), models.UniqueConstraint(fields=('mobile',), name='unique_active_mobile')],
            },
        ),
    ]
