# Generated by Django 5.2.1 on 2025-05-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('completion_report', models.TextField(max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('workin_hours', models.CharField(blank=True, max_length=220, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
